USE [master]
GO

/****** Object:  Database [Inkasso]    Script Date: 2021-12-31 09:19:28 ******/
CREATE DATABASE [Inkasso]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Inkasso', FILENAME = N'C:\Users\NissesR\Inkasso.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Inkasso_log', FILENAME = N'C:\Users\NissesR\Inkasso_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Inkasso].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Inkasso] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Inkasso] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Inkasso] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Inkasso] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Inkasso] SET ARITHABORT OFF 
GO

ALTER DATABASE [Inkasso] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Inkasso] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Inkasso] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Inkasso] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Inkasso] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Inkasso] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Inkasso] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Inkasso] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Inkasso] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Inkasso] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Inkasso] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Inkasso] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Inkasso] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Inkasso] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Inkasso] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Inkasso] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Inkasso] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Inkasso] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Inkasso] SET  MULTI_USER 
GO

ALTER DATABASE [Inkasso] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Inkasso] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Inkasso] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Inkasso] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Inkasso] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Inkasso] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Inkasso] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Inkasso] SET  READ_WRITE 
GO

