/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

INSERT INTO TeamTypes (Name) VALUES ('DO');
INSERT INTO TeamTypes (Name) VALUES ('MO');
INSERT INTO TeamTypes (Name) VALUES ('PO');
INSERT INTO TeamTypes (Name) VALUES ('Support');
INSERT INTO RoleTypes (Name) VALUES ('Agile');
INSERT INTO RoleTypes (Name) VALUES ('SM3');

INSERT INTO Teams (name,TeamTypeId) VALUES('Business Platforms','1')
INSERT INTO Teams (name,TeamTypeId) VALUES('Core Infrastruktur','1')
INSERT INTO Teams (name,TeamTypeId) VALUES('Digihub','3')
INSERT INTO Teams (name,TeamTypeId) VALUES('Digital arbetsplats','3')
INSERT INTO Teams (name,TeamTypeId) VALUES('Entreprenad','3')
INSERT INTO Teams (name,TeamTypeId) VALUES('Finans','3')
INSERT INTO Teams (name,TeamTypeId) VALUES('Global Platforms','1')
INSERT INTO Teams (name,TeamTypeId) VALUES('Global Services','1')
INSERT INTO Teams (name,TeamTypeId) VALUES('HR','3')
INSERT INTO Teams (name,TeamTypeId) VALUES('Information & Data Management','3')
INSERT INTO Teams (name,TeamTypeId) VALUES('Inköp','3')
INSERT INTO Teams (name,TeamTypeId) VALUES('ITLT','4')
INSERT INTO Teams (name,TeamTypeId) VALUES('LACE','4')
INSERT INTO Teams (name,TeamTypeId) VALUES('Marknad & Försäljning​','3')
INSERT INTO Teams (name,TeamTypeId) VALUES('Maskinuthyrning','3')
INSERT INTO Teams (name,TeamTypeId) VALUES('Nordic Workplace','3')
INSERT INTO Teams (name,TeamTypeId) VALUES('Service Desk','1')
INSERT INTO Teams (name,TeamTypeId) VALUES('TUI','3')
INSERT INTO Teams (name,TeamTypeId) VALUES('Uppdragsverksamhet','3')

INSERT INTO Roles (name,RoleTypeId) VALUES('Scrum Master','1')
INSERT INTO Roles (name,RoleTypeId) VALUES('Architect','1')
INSERT INTO Roles (name,RoleTypeId) VALUES('Team','1')
INSERT INTO Roles (name,RoleTypeId) VALUES('Business Owner','1')
INSERT INTO Roles (name,RoleTypeId) VALUES('Product Management','1')
INSERT INTO Roles (name,RoleTypeId) VALUES('Product Owner','1')
INSERT INTO Roles (name,RoleTypeId) VALUES('STE','1')
INSERT INTO Roles (name,RoleTypeId) VALUES('Arkitekt','2')
INSERT INTO Roles (name,RoleTypeId) VALUES('ITSM','2')
INSERT INTO Roles (name,RoleTypeId) VALUES('ITSO','2')
INSERT INTO Roles (name,RoleTypeId) VALUES('Processledare','2')
INSERT INTO Roles (name,RoleTypeId) VALUES('Processpecialist','2')
INSERT INTO Roles (name,RoleTypeId) VALUES('Processägare','2')
INSERT INTO Roles (name,RoleTypeId) VALUES('Produktägare','2')
INSERT INTO Roles (name,RoleTypeId) VALUES('SR','2')

INSERT INTO Employees (email, firstname, lastname) VALUES('tomas.ackebjer@skanska.se','Tomas','Ackebjer')
INSERT INTO Employees (email, firstname, lastname) VALUES('anders.a.ahlberg@skanska.se','Anders','Ahlberg')
INSERT INTO Employees (email, firstname, lastname) VALUES('mikael.ahlqvist@skanska.se','Mikael','Ahlqvist')
INSERT INTO Employees (email, firstname, lastname) VALUES('mathias.alwart@skanska.se','Mathias','Alwart')
INSERT INTO Employees (email, firstname, lastname) VALUES('Malin.Andersson@Skanska.se','Malin','Andersson')
INSERT INTO Employees (email, firstname, lastname) VALUES('Inger.Andersson@Skanska.se','Inger','Andersson')
INSERT INTO Employees (email, firstname, lastname) VALUES('linn.areno@skanska.se','Linn','Areno')
INSERT INTO Employees (email, firstname, lastname) VALUES('jessica.axelsson@skanska.se','Jessica ','Axelsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('henrik.axelsson@skanska.se','Henrik','Axelsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('cecilia.backa@skanska.se','Cecilia','Backa')
INSERT INTO Employees (email, firstname, lastname) VALUES('johan.bellander@skanska.se','johan','bellander')
INSERT INTO Employees (email, firstname, lastname) VALUES('Jan.Bendes@skanska.se','Jan','Bendes')
INSERT INTO Employees (email, firstname, lastname) VALUES('saara.bengtsson@skanska.se','Saara','Bengtsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('felix.bengtsson@skanska.se','Felix','Bengtsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('veronica.berggren@skanska.se','Veronica','Berggren')
INSERT INTO Employees (email, firstname, lastname) VALUES('emanuel.berggren@skanska.se','Emanuel','Berggren ')
INSERT INTO Employees (email, firstname, lastname) VALUES('aristarchos.betsis@skanska.se','Aristarchos','Betsis')
INSERT INTO Employees (email, firstname, lastname) VALUES('mikael.bjorklund@skanska.se','Mikael','Björklund')
INSERT INTO Employees (email, firstname, lastname) VALUES('Johan.Bjorksater@Skanska.se','Johan','Björksäter')
INSERT INTO Employees (email, firstname, lastname) VALUES('peter.blomberg@skanska.se','Peter','Blomberg')
INSERT INTO Employees (email, firstname, lastname) VALUES('magnus.blomberg@skanska.se','Magnus','Blomberg')
INSERT INTO Employees (email, firstname, lastname) VALUES('per.bostrom@skanska.se','Per','Boström')
INSERT INTO Employees (email, firstname, lastname) VALUES('jonna.brattlow@skanska.se','Jonna ','Brattlöw')
INSERT INTO Employees (email, firstname, lastname) VALUES('Benny.Brodin@skanska.se','Benny','Brodin ')
INSERT INTO Employees (email, firstname, lastname) VALUES('stefan.brohlin@skanska.se','Stefan','Brohlin')
INSERT INTO Employees (email, firstname, lastname) VALUES('peter.bronnvall@skanska.se','Peter','Bronnvall')
INSERT INTO Employees (email, firstname, lastname) VALUES('maria.campo@skanska.se','Maria','Campo')
INSERT INTO Employees (email, firstname, lastname) VALUES('karam.chammas@skanska.se','Karam','Chammas')
INSERT INTO Employees (email, firstname, lastname) VALUES('sunny.chugh@skanska.se','Sunny','Chugh')
INSERT INTO Employees (email, firstname, lastname) VALUES('mathias.dackheden@skanska.se','Mathias','Dackheden ')
INSERT INTO Employees (email, firstname, lastname) VALUES('hakan.danielsson@skanska.se','Håkan','Danielsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('jonas.davidsson@boklok.se','Jonas','Davidsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('mats.dunmar@skanska.se','Mats','Dunmar')
INSERT INTO Employees (email, firstname, lastname) VALUES('tomas.eklof@skanska.se','Thomas','Eklöf')
INSERT INTO Employees (email, firstname, lastname) VALUES('ann.ericsson@skanska.se','Ann','Ericsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('claes.erikhaus@skanska.se','Claes','Erikhaus')
INSERT INTO Employees (email, firstname, lastname) VALUES('christian.c.eriksson@skanska.se','Christian','Eriksson ')
INSERT INTO Employees (email, firstname, lastname) VALUES('Per.Fagerberg@Skanska.se','Per','Fagerberg')
INSERT INTO Employees (email, firstname, lastname) VALUES('magnus.fagerstrom@skanska.se','Magnus','Fagerström')
INSERT INTO Employees (email, firstname, lastname) VALUES('Anders.Ferm@skanska.se','Anders','Ferm')
INSERT INTO Employees (email, firstname, lastname) VALUES('fredrik.fjellstrom@skanska.se','Fredrik','Fjellström')
INSERT INTO Employees (email, firstname, lastname) VALUES('carl-johan.fryxell@skanska.se','Carl-Johan','Fryxell')
INSERT INTO Employees (email, firstname, lastname) VALUES('Robert.Green@skanska.se','Robert','Green')
INSERT INTO Employees (email, firstname, lastname) VALUES('carl.grennes@skanska.no','Carl','Grennes ')
INSERT INTO Employees (email, firstname, lastname) VALUES('Per-Eric.Grans@Skanska.se','Per-Eric','Gräns')
INSERT INTO Employees (email, firstname, lastname) VALUES('rickard.gunnarsson@skanska.se','Rickard (IT) ','Gunnarsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('jorgen.s.gustavsson@skanska.se','Jörgen','Gustavsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('elin.gange@skanska.se','Elin','Gånge')
INSERT INTO Employees (email, firstname, lastname) VALUES('oscar.hallstrom@skanska.se','Oscar','Hallström')
INSERT INTO Employees (email, firstname, lastname) VALUES('Henrik.Hassler@skanska.se','Henrik','Hassler')
INSERT INTO Employees (email, firstname, lastname) VALUES('patrick.hedren@skanska.se','Patrick','Hedren')
INSERT INTO Employees (email, firstname, lastname) VALUES('camilla.hemmingsen@skanska.se','Camilla','Hemmingsen')
INSERT INTO Employees (email, firstname, lastname) VALUES('jacob.henricson@skanska.se','Jacob','Henricson')
INSERT INTO Employees (email, firstname, lastname) VALUES('patrik.herbertsson@skanska.se','Patrik','Herbertsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('susanne.holmberg@skanska.se','Susanne','Holmberg')
INSERT INTO Employees (email, firstname, lastname) VALUES('matias.hovi@skanska.fi','Matias','Hovi')
INSERT INTO Employees (email, firstname, lastname) VALUES('osborn.harmestad@skanska.se','Osborn','Härmestad')
INSERT INTO Employees (email, firstname, lastname) VALUES('martin.horestrand@skanska.se','Martin','Hörestrand')
INSERT INTO Employees (email, firstname, lastname) VALUES('malin.hormanseder@skanska.se','Malin','Hörmanseder')
INSERT INTO Employees (email, firstname, lastname) VALUES('marcos.ivulic@skanska.se','Marcos','ivulic')
INSERT INTO Employees (email, firstname, lastname) VALUES('alexander.janving@skanska.se','Alexander','Janving')
INSERT INTO Employees (email, firstname, lastname) VALUES('daniel.jensen@skanska.se','Daniel','Jensen')
INSERT INTO Employees (email, firstname, lastname) VALUES('andreas.c.johansson@skanska.se','Andreas','Johansson')
INSERT INTO Employees (email, firstname, lastname) VALUES('Roger.A.Johansson@Skanska.se','Roger','Johansson')
INSERT INTO Employees (email, firstname, lastname) VALUES('Anders.O.Johansson@Skanska.se','Anders','Johansson')
INSERT INTO Employees (email, firstname, lastname) VALUES('henric.johansson@skanska.se','Henric','Johansson')
INSERT INTO Employees (email, firstname, lastname) VALUES('Ronnie.Johansson@Skanska.se','Ronnie','Johansson')
INSERT INTO Employees (email, firstname, lastname) VALUES('Eva-Christine.Jonsson@Skanska.se','Eva-Christine','Jonsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('malin.jonsson@skanska.se','Malin','Jönsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('morgan.jonsson@skanska.se','Morgan','Jönsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('jeff.kantus@skanska.se','Jeff','Kantus')
INSERT INTO Employees (email, firstname, lastname) VALUES('andreas.p.karlsson@skanska.se','Andreas','Karlsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('reza.ketabchi@skanska.se','Reza','Katabchi')
INSERT INTO Employees (email, firstname, lastname) VALUES('reza.ketabchi@skanska.se','Reza','Ketabchi')
INSERT INTO Employees (email, firstname, lastname) VALUES('Josef.Kallstrom@skanska.se','Josef','Källström')
INSERT INTO Employees (email, firstname, lastname) VALUES('robin.lagerstrom@skanska.se','Robin','Lagerström')
INSERT INTO Employees (email, firstname, lastname) VALUES('tommy.lahtela@skanska.se','Tommy','Lahtela ')
INSERT INTO Employees (email, firstname, lastname) VALUES('karin.leander@skanska.se','Karin','Leander')
INSERT INTO Employees (email, firstname, lastname) VALUES('erik.lehto@skanska.se','Erik','Lehto')
INSERT INTO Employees (email, firstname, lastname) VALUES('goran.liljeberg@skanska.se','Göran ','Liljeberg')
INSERT INTO Employees (email, firstname, lastname) VALUES('michael.lind@skanska.se','Michael','Lind')
INSERT INTO Employees (email, firstname, lastname) VALUES('niclas.lindholm@skanska.se','Niclas','Lindholm')
INSERT INTO Employees (email, firstname, lastname) VALUES('magnus.lindqvist@skanska.se','Magnus','Lindqvist')
INSERT INTO Employees (email, firstname, lastname) VALUES('christer.lindstrom@skanska.se','Christer','Lindström')
INSERT INTO Employees (email, firstname, lastname) VALUES('linus.ljungberg@skanska.se','Linus','Ljungberg')
INSERT INTO Employees (email, firstname, lastname) VALUES('alice.loberg@skanska.se','Alice','Loberg')
INSERT INTO Employees (email, firstname, lastname) VALUES('hanna.lorentzon@skanska.se','Hanna','Lorentzon')
INSERT INTO Employees (email, firstname, lastname) VALUES('anders.ludvigsson@boklok.se','Anders','Ludvigsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('Kristofer.Lundblad@Skanska.se','Kristofer','Lundblad')
INSERT INTO Employees (email, firstname, lastname) VALUES('Frans.Lundgren@skanska.se','Frans','Lundgren')
INSERT INTO Employees (email, firstname, lastname) VALUES('Veronica.Lundqvist@Skanska.se','Veronica ','Lundqvist')
INSERT INTO Employees (email, firstname, lastname) VALUES('henrik.magnusson@skanska.se','Henrik','Magnusson')
INSERT INTO Employees (email, firstname, lastname) VALUES('brinda.maiti@skanska.se','Brinda','Maiti')
INSERT INTO Employees (email, firstname, lastname) VALUES('matthias.malmros@skanska.se','Matthias','Malmros')
INSERT INTO Employees (email, firstname, lastname) VALUES('cristian.malmros@skanska.se','Christian','Malmros')
INSERT INTO Employees (email, firstname, lastname) VALUES('Lars.Marmestedt@Skanska.se','Lars','Marmestedt')
INSERT INTO Employees (email, firstname, lastname) VALUES('joel.millbert@skanska.se','Joel','Millbert')
INSERT INTO Employees (email, firstname, lastname) VALUES('anatoly.mironov@skanska.se','Anatoly','Mironov')
INSERT INTO Employees (email, firstname, lastname) VALUES('petra.mard@skanska.se','Petra','Mård')
INSERT INTO Employees (email, firstname, lastname) VALUES('Marcus.Nilsson@skanska.se','Marcus','Nilsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('thomas.tn.nilsson@skanska.se','Thomas','Nilsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('pelle.nilsson@skanska.se','Pelle','Nilsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('johanna.j.nilsson@skanska.se','Johanna','Nilsson ')
INSERT INTO Employees (email, firstname, lastname) VALUES('eric.nilsson@skanska.se','Eric','Nilsson ')
INSERT INTO Employees (email, firstname, lastname) VALUES('ing-marie.nilsson@skanska.se','Ing-Marie','Nilsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('rickard.nisses-gagner@skanska.se','Rickard','Nisses-Gagnér')
INSERT INTO Employees (email, firstname, lastname) VALUES('gustav.nyman@skanska.se','Gustav','Nyman')
INSERT INTO Employees (email, firstname, lastname) VALUES('jonas.nywall@skanska.se','Jonas','Nywall')
INSERT INTO Employees (email, firstname, lastname) VALUES('petter.odin.hestvik@skanska.se','Petter','Odin Hestvik')
INSERT INTO Employees (email, firstname, lastname) VALUES('calle.olsson@skanska.se','Calle','Olsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('sia.otterstrom@skanska.se','Sia','Otterström')
INSERT INTO Employees (email, firstname, lastname) VALUES('Goran.Pajnic@skanska.se','Goran','Pajnic')
INSERT INTO Employees (email, firstname, lastname) VALUES('louise.palmgren@skanska.se','Louise','Palmgren')
INSERT INTO Employees (email, firstname, lastname) VALUES('patricia.paredes@skanska.se','Patricia','Paredes')
INSERT INTO Employees (email, firstname, lastname) VALUES('Jonas.Persson@Skanska.se','Jonas','Persson')
INSERT INTO Employees (email, firstname, lastname) VALUES('eva.philip@skanska.se','Eva','Philip')
INSERT INTO Employees (email, firstname, lastname) VALUES('mats.renner@skanska.se','Mats','Renner')
INSERT INTO Employees (email, firstname, lastname) VALUES('taco.rensink@skanska.se','Taco','Rensik')
INSERT INTO Employees (email, firstname, lastname) VALUES('gustav.ribbing@skanska.se','Gustav','Ribbing')
INSERT INTO Employees (email, firstname, lastname) VALUES('ann-margret.ring@skanska.se','Ann-Margreth','Ring')
INSERT INTO Employees (email, firstname, lastname) VALUES('sandra.rocklind@skanska.se','Sandra','Rocklind')
INSERT INTO Employees (email, firstname, lastname) VALUES('conny.roll@Skanska.se','Conny','Roll')
INSERT INTO Employees (email, firstname, lastname) VALUES('gabriella.rosen@skanska.se','Gabriella','Rosén ')
INSERT INTO Employees (email, firstname, lastname) VALUES('katarina.rosenqvist@skanska.se','Katarina','Rosenkvist')
INSERT INTO Employees (email, firstname, lastname) VALUES('fredrik.rusch@skanska.se','Fredrik','Rusch')
INSERT INTO Employees (email, firstname, lastname) VALUES('erik.rasberg@skanska.se','Erik','Råsberg')
INSERT INTO Employees (email, firstname, lastname) VALUES('jonna.rastedt@skanska.se','Jonna','Råstedt')
INSERT INTO Employees (email, firstname, lastname) VALUES('debarati.sadhukhan@skanska.se','Debarati','Sadhukhan')
INSERT INTO Employees (email, firstname, lastname) VALUES('daniel.palsson@skanska.se','Linn','Samuelsen')
INSERT INTO Employees (email, firstname, lastname) VALUES('andreas.sandberg@everest.se','Andreas','Sandberg')
INSERT INTO Employees (email, firstname, lastname) VALUES('linda.sandin@skanska.se','Linda','Sandin')
INSERT INTO Employees (email, firstname, lastname) VALUES('Johan.Schjelderup@Skanska.se','Johan','Schelderup')
INSERT INTO Employees (email, firstname, lastname) VALUES('johanna.schledermann@skanska.se','Johanna','Schlederman')
INSERT INTO Employees (email, firstname, lastname) VALUES('pamela.seward@skanska.se','Pamela','Seward')
INSERT INTO Employees (email, firstname, lastname) VALUES('emil.signal@skanska.se','Emil','Signal')
INSERT INTO Employees (email, firstname, lastname) VALUES('daniel.sillen@skanska.se','Daniel','Sillén')
INSERT INTO Employees (email, firstname, lastname) VALUES('helena.sjolander@skanska.se','Helena','Sjölander')
INSERT INTO Employees (email, firstname, lastname) VALUES('ulrika.sjostrom.johnsson@skanska.se','Ulrika','Sjöström Johnsson')
INSERT INTO Employees (email, firstname, lastname) VALUES('sofia.skoglosa@skanska.se','Sofia','Skoglösa')
INSERT INTO Employees (email, firstname, lastname) VALUES('christel.skoog@skanska.se','Christel','Skoog')
INSERT INTO Employees (email, firstname, lastname) VALUES('hakan.smeds@skanska.se','Håkan','Smeds')
INSERT INTO Employees (email, firstname, lastname) VALUES('patrik.p.stenback@skanska.se','Patrik','Stenback')
INSERT INTO Employees (email, firstname, lastname) VALUES('johan.stengard@skanska.se','Johan ','Stengård')
INSERT INTO Employees (email, firstname, lastname) VALUES('hanna.stigmer@skanska.se','Hanna','Stigmer')
INSERT INTO Employees (email, firstname, lastname) VALUES('Mikael.Stohm@Skanska.se','Mikael','Stohm')
INSERT INTO Employees (email, firstname, lastname) VALUES('ludwig.stromstedt@skanska.se','Ludwig','Strömstedt')
INSERT INTO Employees (email, firstname, lastname) VALUES('helene.sundh@skanska.se','Helene','Sundh')
INSERT INTO Employees (email, firstname, lastname) VALUES('Rolf.Sundstrom@Skanska.se','Rolf','Sundström')
INSERT INTO Employees (email, firstname, lastname) VALUES('izabela.surmacz@skanska.se','Izabela','Surmacz')
INSERT INTO Employees (email, firstname, lastname) VALUES('henrik.svensson@skanska.se','Henrik','Svensson')
INSERT INTO Employees (email, firstname, lastname) VALUES('Anna.Safwenberg@skanska.se','Anna','Säfwenberg')
INSERT INTO Employees (email, firstname, lastname) VALUES('martin.soderberg@skanska.se','Martin','Söderberg ')
INSERT INTO Employees (email, firstname, lastname) VALUES('staffan.soderberg@skanska.se','Staffan','Söderberg')
INSERT INTO Employees (email, firstname, lastname) VALUES('anna.soderling@skanska.se','Anna','Söderling')
INSERT INTO Employees (email, firstname, lastname) VALUES('niklas.soderqvist@skanska.se','Niklas','Söderqvist')
INSERT INTO Employees (email, firstname, lastname) VALUES('henrik.sorensen@skanska.no','Henrik Skar ','Sørensen')
INSERT INTO Employees (email, firstname, lastname) VALUES('tina.taipale@skanska.se','Tina','Taipale')
INSERT INTO Employees (email, firstname, lastname) VALUES('glenn.thunblad@skanska.se','Glenn','Thunblad')
INSERT INTO Employees (email, firstname, lastname) VALUES('erik.vanderstad@skanska.se','Erik','Van Der stad')
INSERT INTO Employees (email, firstname, lastname) VALUES('alexander.velevski@boklok.se','Alexander','Velevski')
INSERT INTO Employees (email, firstname, lastname) VALUES('anton.vukoje@skanska.se','Anton','Vukoje')
INSERT INTO Employees (email, firstname, lastname) VALUES('karin.k.wallmark@skanska.se','Karin','Wallmark')
INSERT INTO Employees (email, firstname, lastname) VALUES('Eva.Walther@Skanska.se','Eva','Walther')
INSERT INTO Employees (email, firstname, lastname) VALUES('margareta.welin@skanska.se','Margareta','Welin')
INSERT INTO Employees (email, firstname, lastname) VALUES('mattias.Wendel@skanska.se','Mattias','Wendel')
INSERT INTO Employees (email, firstname, lastname) VALUES('helene.Wenster@skanska.se','Helene','Wenster')
INSERT INTO Employees (email, firstname, lastname) VALUES('marcus.Weurlander@skanska.se','Marcus','Weurlander')
INSERT INTO Employees (email, firstname, lastname) VALUES('pernilla.widlund@skanska.se','Pernilla','Widlund')
INSERT INTO Employees (email, firstname, lastname) VALUES('sofie.akesson@skanska.se','Sofie','Åkesson ')
INSERT INTO Employees (email, firstname, lastname) VALUES('Annika.Ohlund@Skanska.se','Annika','Öhlund')
